CREATE TABLE alunos (
	id LONG AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    cpf VARCHAR(15) UNIQUE NOT NULL,
    curso INT NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    endereco VARCHAR(255)
);